import formModel from "./formModel";

const {
  formField: {
    first_name,
    last_name,
    email,
    gitHub,
    phone,
    // US_resident,
    physical_zipcode,
    physical_address_1,
    physical_address_2,
    physical_city,
    physical_state,
    physical_country,
    // mailing_same,
    mailing_zipcode,
    mailing_address_1,
    mailing_address_2,
    mailing_city,
    mailing_state,
    mailing_country,
    dob,
    pronouns,
    gender_identity,
    gender_identity_self,
    race_ethnicity,
    race_ethnicity_self,
    education,
    spoken_languages,
    employed,
    in_school,
    low_income,
    emergency_contact_1_name,
    emergency_contact_1_relationship,
    emergency_contact_1_phone,
    emergency_contact_2_name,
    emergency_contact_2_relationship,
    emergency_contact_2_phone,
    learning_style,
    prior_coding_education,
    prior_coding_languages,
    work_commitment_consent,
    leave_notice_consent,
  },
} = formModel;

export default {
  [first_name.name]: "",
  [last_name.name]: "",
  [email.name]: "",
  [gitHub.name]: "",
  [phone.name]: "",
  //   [US_resident.name]: "",
  [physical_zipcode.name]: "",
  [physical_address_1.name]: "",
  [physical_address_2.name]: "",
  [physical_city.name]: "",
  [physical_state.name]: "",
  [physical_country.name]: "",
  //   [mailing_same.name]: false,
  [mailing_zipcode.name]: "",
  [mailing_address_1.name]: "",
  [mailing_address_2.name]: "",
  [mailing_city.name]: "",
  [mailing_state.name]: "",
  [mailing_country.name]: "",
  [dob.name]: "",
  [pronouns.name]: "",
  [gender_identity.name]: "",
  [gender_identity_self.name]: "",
  [race_ethnicity.name]: "",
  [race_ethnicity_self.name]: "",
  [education.name]: "",
  [spoken_languages.name]: "",
  [employed.name]: "",
  [in_school.name]: "",
  [low_income.name]: "",
  [emergency_contact_1_name.name]: "",
  [emergency_contact_1_relationship.name]: "",
  [emergency_contact_1_phone.name]: "",
  [emergency_contact_2_name.name]: "",
  [emergency_contact_2_relationship.name]: "",
  [emergency_contact_2_phone.name]: "",
  [learning_style.name]: [],
  [prior_coding_education.name]: "",
  [prior_coding_languages.name]: [],
  [work_commitment_consent.name]: false,
  [leave_notice_consent.name]: false,
};
