import formModel from "./formModel";

const {
  formField: {
    firstName,
    lastName,
    email,
    gitHub,
    phone,
    USResident,
    physicalZipcode,
    physicalAddress1,
    physicalAddress2,
    physicalCity,
    physicalState,
    physicalCountry,
    mailingSame,
    mailingZipcode,
    mailingAddress1,
    mailingAddress2,
    mailingCity,
    mailingState,
    mailingCountry,
    dob,
    pronouns,
    genderIdentity,
    genderIdentitySelf,
    raceEthnicity,
    raceEthnicitySelf,
    education,
    spokenLanguages,
    employed,
    inSchool,
    lowIncome,
    emergencyContact1Name,
    emergencyContact1Relationship,
    emergencyContact1Phone,
    emergencyContact2Name,
    emergencyContact2Relationship,
    emergencyContact2Phone,
    learningStyle,
    priorCodingEducation,
    priorCodingLanguages,
    workCommitmentConsent,
    leaveNoticeConsent,
  },
} = formModel;

export default {
  [firstName.name]: "",
  [lastName.name]: "",
  [email.name]: "",
  [gitHub.name]: "",
  [phone.name]: "",
  [USResident.name]: "",
  [physicalZipcode.name]: "",
  [physicalAddress1.name]: "",
  [physicalAddress2.name]: "",
  [physicalCity.name]: "",
  [physicalState.name]: "",
  [physicalCountry.name]: {},
  [mailingSame.name]: false,
  [mailingZipcode.name]: "",
  [mailingAddress1.name]: "",
  [mailingAddress2.name]: "",
  [mailingCity.name]: "",
  [mailingState.name]: "",
  [mailingCountry.name]: {},
  [dob.name]: "",
  [pronouns.name]: "",
  [genderIdentity.name]: [],
  [genderIdentitySelf.name]: "",
  [raceEthnicity.name]: "",
  [raceEthnicitySelf.name]: "",
  [education.name]: "",
  [spokenLanguages.name]: "",
  [employed.name]: "",
  [inSchool.name]: "",
  [lowIncome.name]: "",
  [emergencyContact1Name.name]: "",
  [emergencyContact1Relationship.name]: "",
  [emergencyContact1Phone.name]: "",
  [emergencyContact2Name.name]: "",
  [emergencyContact2Relationship.name]: "",
  [emergencyContact2Phone.name]: "",
  [learningStyle.name]: [],
  [priorCodingEducation.name]: "",
  [priorCodingLanguages.name]: [],
  [workCommitmentConsent.name]: false,
  [leaveNoticeConsent.name]: false,
};
