export const inputFormElements = [
  {
    name: "firstName",
    placeholder: "Firstname",
    label: "Fist Name",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "lastName",
    placeholder: "Lastname",
    label: "Last Name",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "pronouns",
    placeholder: "He-Him, She-Her",
    label: "Pronouns",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "techStack",
    placeholder: "Node.js, AngularJS, React, Bootstrap, jQuery",
    label: "Tech Stack",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "skills",
    placeholder: "HTML, CSS, JavaScript, Teamwork, Problem-solving",
    label: "Skills",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "previousIndustry",
    placeholder: "Manufacture, Customer Service, Health Care, ...",
    label: "Previous Industry",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "email",
    type: "email",
    placeholder: "example@test.com",
    label: "Email",
    variant: "outlined",
    fullWidth: true,
    required: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "facebook",
    placeholder: "@example.test",
    label: "Facebook",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "github",
    placeholder: "example.test@github.com",
    label: "GitHub",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "linkedin",
    placeholder: "example.test@linkedin.com",
    label: "LinkedIn",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "twitter",
    placeholder: "example.test@twitter.com",
    label: "Twitter",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
  {
    name: "videoUrl",
    type: "link",
    placeholder: "Url video link",
    label: "Video",
    variant: "outlined",
    fullWidth: true,
    xs: 12,
    sm: 6,
    size: "small",
    InputLabelProps: { shrink: true },
  },
];
